// <auto-generated />
using InoviceProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InoviceProject.Migrations
{
    [DbContext(typeof(InvoiceDBContext))]
    partial class InvoiceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InoviceProject.Models.tblCategory", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.HasKey("Category_id");

                    b.HasIndex("Category_name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InoviceProject.Models.tblCompanyDetails", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gst_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("company_id");

                    b.ToTable("CompanyDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblCustomer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customer_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InoviceProject.Models.tblInvoice_Product", b =>
                {
                    b.Property<int>("invoice_product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("invoice_product_id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("invoice_id")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("invoice_product_id");

                    b.HasIndex("invoice_id");

                    b.HasIndex("product_id");

                    b.ToTable("Invoice_Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblInvoice_details", b =>
                {
                    b.Property<int>("invoice_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("invoice_id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<float>("invoice_amount")
                        .HasColumnType("real");

                    b.Property<string>("invoice_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("invoice_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Invoice_Details");
                });

            modelBuilder.Entity("InoviceProject.Models.tblLocation", b =>
                {
                    b.Property<int>("Location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Location_id"));

                    b.Property<string>("Location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_details", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<bool>("Is_Received")
                        .HasColumnType("bit");

                    b.Property<string>("order_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vendor_id")
                        .HasColumnType("int");

                    b.HasKey("order_id");

                    b.HasIndex("vendor_id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_items", b =>
                {
                    b.Property<int>("orderitem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderitem_id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("Order_quantity")
                        .HasColumnType("int");

                    b.Property<int>("Product_id")
                        .HasColumnType("int");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.HasKey("orderitem_id");

                    b.HasIndex("Product_id");

                    b.HasIndex("order_id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InoviceProject.Models.tblProduct", b =>
                {
                    b.Property<int>("Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_id"));

                    b.Property<string>("Product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Selling_rate")
                        .HasColumnType("real");

                    b.Property<int>("Stock_quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubCategory_id")
                        .HasColumnType("int");

                    b.Property<float>("Tax")
                        .HasColumnType("real");

                    b.Property<int>("Unit_id")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<int>("flag")
                        .HasColumnType("int");

                    b.HasKey("Product_id");

                    b.HasIndex("SubCategory_id");

                    b.HasIndex("Unit_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblReceived_Items", b =>
                {
                    b.Property<int>("received_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("received_item_id"));

                    b.Property<float>("Purchase_rate")
                        .HasColumnType("real");

                    b.Property<int>("Receive_id")
                        .HasColumnType("int");

                    b.Property<int>("flag")
                        .HasColumnType("int");

                    b.Property<int>("orderitem_id")
                        .HasColumnType("int");

                    b.Property<int>("received_quantity")
                        .HasColumnType("int");

                    b.HasKey("received_item_id");

                    b.HasIndex("Receive_id");

                    b.HasIndex("orderitem_id");

                    b.ToTable("ReceivedItems");
                });

            modelBuilder.Entity("InoviceProject.Models.tblReceived_details", b =>
                {
                    b.Property<int>("Receive_stock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Receive_stock_id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("Order_id")
                        .HasColumnType("int");

                    b.Property<string>("Received_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Receive_stock_id");

                    b.HasIndex("Order_id");

                    b.ToTable("ReceivedDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblSubCategory", b =>
                {
                    b.Property<int>("SubCategory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategory_id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategory_id");

                    b.HasIndex("Category_id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("InoviceProject.Models.tblUnit", b =>
                {
                    b.Property<int>("Unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unit_id"));

                    b.Property<string>("Unit_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Unit_id");

                    b.HasIndex("Unit_name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("InoviceProject.Models.tblVendor", b =>
                {
                    b.Property<int>("Vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vendor_id"));

                    b.Property<string>("Alternate_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firm_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firm_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<string>("Mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vendor_id");

                    b.HasIndex("Location_id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("InoviceProject.Models.tblinvoice_payments", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("payment_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("invoice_id")
                        .HasColumnType("int");

                    b.Property<double>("payment_amount")
                        .HasColumnType("float");

                    b.Property<string>("payment_date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment_mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("payment_id");

                    b.HasIndex("invoice_id");

                    b.ToTable("Invoice_Payments");
                });

            modelBuilder.Entity("InoviceProject.Models.tblInvoice_Product", b =>
                {
                    b.HasOne("InoviceProject.Models.tblInvoice_details", "Invoice_Details")
                        .WithMany("Invoice_Products")
                        .HasForeignKey("invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InoviceProject.Models.tblProduct", "Products")
                        .WithMany("Invoice_Products")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice_Details");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblInvoice_details", b =>
                {
                    b.HasOne("InoviceProject.Models.tblCustomer", "Customers")
                        .WithMany("Invoice_Details")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_details", b =>
                {
                    b.HasOne("InoviceProject.Models.tblVendor", "Vendors")
                        .WithMany("OrderDetails")
                        .HasForeignKey("vendor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_items", b =>
                {
                    b.HasOne("InoviceProject.Models.tblProduct", "Products")
                        .WithMany("OrderItems")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InoviceProject.Models.tblOrder_details", "OrderDetails")
                        .WithMany("OrderItems")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetails");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblProduct", b =>
                {
                    b.HasOne("InoviceProject.Models.tblSubCategory", "SubCategories")
                        .WithMany("Products")
                        .HasForeignKey("SubCategory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InoviceProject.Models.tblUnit", "Units")
                        .WithMany("Products")
                        .HasForeignKey("Unit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategories");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("InoviceProject.Models.tblReceived_Items", b =>
                {
                    b.HasOne("InoviceProject.Models.tblReceived_details", "ReceivedDetails")
                        .WithMany("ReceivedItems")
                        .HasForeignKey("Receive_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InoviceProject.Models.tblOrder_items", "OrderItems")
                        .WithMany("ReceivedItems")
                        .HasForeignKey("orderitem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("ReceivedDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblReceived_details", b =>
                {
                    b.HasOne("InoviceProject.Models.tblOrder_details", "OrderDetails")
                        .WithMany("ReceivedDetails")
                        .HasForeignKey("Order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblSubCategory", b =>
                {
                    b.HasOne("InoviceProject.Models.tblCategory", "Categories")
                        .WithMany("SubCategories")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("InoviceProject.Models.tblVendor", b =>
                {
                    b.HasOne("InoviceProject.Models.tblLocation", "Locations")
                        .WithMany("Vendors")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("InoviceProject.Models.tblinvoice_payments", b =>
                {
                    b.HasOne("InoviceProject.Models.tblInvoice_details", "Invoice_Details")
                        .WithMany("Invoice_Payments")
                        .HasForeignKey("invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice_Details");
                });

            modelBuilder.Entity("InoviceProject.Models.tblCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("InoviceProject.Models.tblCustomer", b =>
                {
                    b.Navigation("Invoice_Details");
                });

            modelBuilder.Entity("InoviceProject.Models.tblInvoice_details", b =>
                {
                    b.Navigation("Invoice_Payments");

                    b.Navigation("Invoice_Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblLocation", b =>
                {
                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_details", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ReceivedDetails");
                });

            modelBuilder.Entity("InoviceProject.Models.tblOrder_items", b =>
                {
                    b.Navigation("ReceivedItems");
                });

            modelBuilder.Entity("InoviceProject.Models.tblProduct", b =>
                {
                    b.Navigation("Invoice_Products");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("InoviceProject.Models.tblReceived_details", b =>
                {
                    b.Navigation("ReceivedItems");
                });

            modelBuilder.Entity("InoviceProject.Models.tblSubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblUnit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InoviceProject.Models.tblVendor", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
